### ISSUE TITLE
Stickymenu issue

### ISSUE THREAD

**Issue by Kroellie** [myparcelnl/delivery-options#65]
Using MyParcel 4.1.6-beta.1 and Magento 2.3.5 together with Firecheckout.

We have a sticky horizontal menu in the header.
When we select an address the deliveryoptions show up.
Select pickup location, witness the pickup list expanding, select more options.
Now scroll down to the bottom of the site and witness the stickymenu going awry.

Reason for this is that the angular box isn't adding up to the document size. I tried to observe it with ResizeObserver, but that doesn't play nice with Angular.

I now circumvented it in a different way, but it would be nice for the document to know how high the deliveryoptions container is so that sticky elements remain working.

**Comment by EdieLemoine** [comment]
Hi @Kroellie, thanks for posting an issue. Could you share some more details and maybe screenshots of what you mean? 

You can't reliably predict how tall the container is going to be exactly, because it's based on the configuration and may even vary by date. Can't you just retrieve it afterwards using `HTMLElement.clientHeight` on `form.myparcel-delivery-options`?

**Comment by Kroellie** [comment]
I've sent you a PM in Slack...

**Comment by EdieLemoine** [comment]
If this is still an issue with the 6.x delivery options, please let us know.
